### ISSUE TITLE
スペースだけの行が存在すると、パースに失敗する

### ISSUE THREAD

**Issue by kn1cht** [fabon-f/sb2re#1]
## Summary
半角スペースだけの行（全角スペース、タブ文字でも同様）が存在する文字列を入力すると、`sb2re`がエラーで終了します。
これは、Scrapboxでは何も記入されていない箇条書きの項目として表示されます。

![image](https://user-images.githubusercontent.com/16277200/172739896-21ff1482-1fcb-457c-828a-552677e40b03.png)

## Steps to Reproduce
```bash
$ echo "テストだよ\nあああああ\n \nいいいいい" | sb2re
error: Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'type')
            if (n.type === "line" && n.indent !== 0 && n.nodes[0].type === "quote") {
                                                                  ^
    at generateReView (https://raw.githubusercontent.com/fabon-f/sb2re/master/mod.ts:54:67)
    at scrapboxToReView (https://raw.githubusercontent.com/fabon-f/sb2re/master/mod.ts:172:12)
    at https://raw.githubusercontent.com/fabon-f/sb2re/master/cli.ts:30:16
```

**Comment by fabon-f** [comment]
https://github.com/fabon-f/sb2re/commit/ae650d4ce260e19c88968a2dd31f1750a58bb111
たぶんこれで直ったと思います。

**Comment by kn1cht** [comment]
![](https://raw.githubusercontent.com/colons/lgtm-template/master/gifs/nichijou2.gif)
